export enum TokenMailType {
    REGISTER_USER = "REGISTER_USER",
    REGISTER_ADMIN = "REGISTER_ADMIN",
    PASSWORD_RECOVERY_REQUEST = "PASSWORD_RECOVERY_REQUEST",
    BLOCKED_USER_ATTEMPT_LOGIN = "BLOCKED_USER_ATTEMPT_LOGIN",
}